config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "foods#index"

  get "/foods", to: "foods#index", as: "foods"
  get "/recipes", to: "recipes#index", as: "recipes"
  get "/recipes/:recipe_id", to: "recipes#show", as: "recipes_show"
  get "/public_recipes", to: "public_recipes#index", as: "public_recipes"
  get "/shopping_list", to: "shopping_list#index", as: "shopping_list"

  get "/foods/new", to: "foods#new", as: "new_food"
  post "/foods", to: "foods#create", as: "create_food"
  delete "foods/:food_id", to: "foods#destroy", as: "destroy_food"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipes_foods
  belongs_to :user

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipes_foods
  belongs_to :user

  validates :name, presence: true
  validates :preparation_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods
  has_many :recipes
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @current_user = current_user
    @foods = Food.where(user: current_user)
  end

  def new
    @current_user = current_user
    food = Food.new
    render :new, locals: { food: }
  end

  def create
    food = Food.new(params.require(:food).permit(:name, :quantity, :measurement_unit, :price))
    food.user_id = current_user.id

    if food.save
      flash[:success] = 'Food created successfully'
      redirect_to '/foods'
    else
      flash.now[:error] = 'Error: Food could not be saved'
      render :new, locals: { food: }, status: 422
    end
  end

  def destroy
    food = Food.find(params[:food_id])
    food.destroy
    redirect_to(request.referer)
  rescue StandardError
    flash[:message] = 'Cannot delete, it belongs to a recipe.'
    redirect_to(request.referer)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @current_user = current_user
    @recipes = Recipe.order(updated_at: :desc).where(public: true)
    @food_count = {}
    @price = {}
    RecipeFood.all.includes(%i[recipe food]).each do |rf|
      next unless rf.recipe.public == true

      @food_count[rf.recipe_id] = 0 if @food_count[rf.recipe_id].nil?
      @food_count[rf.recipe_id] += 1
      @price[rf.recipe_id] = 0 if @price[rf.recipe_id].nil?
      @price[rf.recipe_id] += rf.quantity * rf.food.price
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @current_user = current_user
    @recipes = Recipe.where(user: current_user)
  end

  def show
    @current_user = current_user
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where(user: current_user)
  end

  def destroy
    @current_user = current_user
    recipe = Recipe.find(params[:recipe_id])
    recipe.destroy
    redirect_to(request.referer)
  end
end

app/controllers/shopping_list.rb
class ShoppingListController < ApplicationController
  def index; end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :authenticate_user!
  def index
    @current_user = current_user
    load_qs
    Food.where(user: current_user).each do |food|
      @qs[food.id] -= food.quantity unless @qs[food.id].nil?
    end
    @food_count = 0
    @total_price = 0
    @price = {}
    @qs.each do |key, q|
      next unless q.positive?

      @price[key] = q * Food.find(key).price
      @food_count += 1
      @total_price += @price[key]
    end
  end

  def load_qs
    @qs = {}
    RecipeFood.all.includes(recipe: { user: [] }).each do |rf|
      if rf.recipe.user == current_user
        @qs[rf.food_id] = 0 if @qs[rf.food_id].nil?
        @qs[rf.food_id] += rf.quantity
      end
    end
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
# Rubocop asking for a comment here
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<h1 class="hidden">Here is the list Foods for current user</h1>

<div class="food_button_wrapper"><%= button_to 'Add Food', new_food_path, method: :get %></div></div>
<div class="allfoods">
  <ul>
    <li class="listitem">
      <span class="fixedwidth">Food</span>
      <span class="centered">Quantity</span>
      <span class="centered">Measurement Unit</span>
      <span class="centered">Price</span>
      <span class="centered">Action</span>
    </li>
    <% @foods.each do |food| %>
      <li class="listitem">
        <span class="fixedwidth"><%= food.name %></span>
        <span class="centered"><%= food.quantity %></span>
        <span class="centered"><%= food.measurement_unit %></span>
        <span class="centered"><%= food.price %></span>
        <span class="centered"><%= link_to "Delete", "/foods/#{ food.id }", data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/foods/new.html.erb
<div class="newfood">
  <h1>New Food</h1>
  <%= form_with model: food, url: create_food_path, method: :post, local: true, scope: :food do |f| %>
    <div>
      <%= f.label :name %><br>
      <%= f.text_field :name, :size => 60, :required => true %>
    </div>

    <div>
      <%= f.label :quantity %><br>
      <%= f.number_field :quantity, :size => 10, :required => true %>
    </div>

    <div>
      <%= f.label :measurement_unit %><br>
      <%= f.text_field :measurement_unit, :size => 10, :required => true %>
    </div>

    <div>
      <%= f.label :price %><br>
      <%= f.number_field :price, step: 0.01, :size => 10, :required => true %>
    </div>

    <%= f.submit "Add Food" , class: "submit" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <header>
        <div>
          <% if url_for!="/" %>
            <%= link_to "Foods", "/foods" %>
          <% else %>
            Foods
          <% end %>
        </div>
        <div>
          <% if url_for!=recipes_path %>
            <%= link_to "Recipes", "/recipes" %>
          <% else %>
            Recipes
          <% end %>
        </div>
        <div>
          <% if url_for!=public_recipes_path %>
            <%= link_to "Public Recipes", "/public_recipes" %>
          <% else %>
            Public Recipes
          <% end %>
        </div>
        <div>
          <% if url_for!=shopping_list_path %>
            <%= link_to "Shopping List", "/shopping_list" %>
          <% else %>
            Shopping List
          <% end %>
        </div>
      </header>
      <div class="subheader">
        <div>
          <% if url_for!="/users/sign_in" && url_for!="/users/sign_up" %>
            <% if user_signed_in? %>
                Logged in as <strong><%= current_user.name %></strong> |
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
          <% end %>
        </div>
        <div>
          <% flash.each do |type, msg| %>
            <%= msg %>
          <% end %>
        </div>
      </div>
    </nav>
    <section>
      <%= yield %>
    </section>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="hidden">Here is a list of all the public Recipes</div>
<center>
  <h1>Public Recipes</h1>
</center>
<div class="publicrecipes">
  <% @recipes.includes([:user]).each do |recipe| %>
    <div class="onerecipe">
      <div>
        <h2><%= link_to recipe.name, "#{ recipes_path }/#{ recipe.id }" %></h2>
        &nbsp;by <%= recipe.user.name %>
      </div>
      <div>
        Total food items: <%= @food_count[recipe.id] %>
        <br />Total price: <%= @price[recipe.id] %>
      </div>
      <div>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>



  <% @recipes.each do |recipe| %>
    <a href="/recipes/<%= recipe.id%>">
        <div><%= recipe.name %></div>
        <div><%= recipe.description %><div>
        <%= link_to "Remove", "/recipes/#{ recipe.id }", data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %>
      <hr>
    </a>
  <% end %>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in recipes#show</p>

<h1><%= @recipe.name %></h1>

<div class="block">
  <div>
    <p>preparation_time: <%= @recipe.preparation_time %> secs</p>
    <p>cooking_time: <%= @recipe.cooking_time %> secs</p>
    <p>steps: <%= @recipe.description %></p>
  </div>

  <div>public:
    <label class="switch">
      <input type="checkbox">
      <span class="slider round"></span>
    </label>
  </div>
</div>

<div class="block">
  <%=link_to "Generate shopping list"%>
  <%=link_to "Add Ingredient"%>
</div>

<ul>
  <li class="listitem">
    <span class="fixedwidth">Food</span>
    <span class="centered">Quantity</span>
    <span class="centered">Value</span>
    <span class="centered">Actions</span>
  </li>
  <% @foods.each do |food| %>
  <li class="listitem">
    <span class="fixedwidth"><%= food.name %></span>
    <span class="centered"><%= food.measurement_unit %></span>
    <span class="centered"><%= food.price %></span>
    <span class="centered"><%= link_to "Modify", "/foods/#{ food.id }", data: { 'turbo-method': :update, 'turbo-confirm': 'Are you sure?' } %><%= link_to "Delete", "/foods/#{ food.id }", data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %></span>
  </li>
<% end %>

app/views/shopping_list/index.html.erb
<div class="hidden">Here is the shopping list for current user, to do all owned recipes</div>
<center>
<h1>Shopping List</h1>
<div class="shoppinglist">
  <div class="totals">
    <div>Amount of food items to buy: <%= @food_count %></div>
    <div>&nbsp;&nbsp;&nbsp;&nbsp;</div>
    <div>Total value of food needed: <%= @total_price %></div>
  </div>
  <div class="generallist">
    <ul>
      <li class="listitem">
        <span class="fixedwidth">Food</span>
        <span class="centered">Quantity</span>
        <span class="centered">Unit</span>
        <span class="centered">Price</span>
      </li>
      <% @qs.each do |key, q| %>
        <% if q > 0 %>
          <li class="listitem">
            <span class="fixedwidth"><%= Food.find(key).name %></span>
            <span class="centered"><%= q %></span>
            <span class="centered"><%= Food.find(key).measurement_unit %></span>
            <span class="centered"><%= @price[key] %></span>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
</center>